import React from 'react'
import "../components/Help.css"
import Navbar from './Navbar'

import Help_img from "../assets/help.webp"
import Helpful from "../assets/hopeful.png"
 const Help = () => {
  return (
    <>
    {/* <div className='relative'>lmao</div> */}
     <div className='nav_top'> 
    <Navbar/>
    </div>
    <div className='flex flex-col justify-center items-center'>
   
   
    <div className='help_container flex'>

<div className='f_helpcon flex flex-col gap-3'>
<h1 className='font-bold text-2xl'>CONTACT</h1>
{/* <br></br> */}
<div className='line'></div>
<div><i>*TITLE*</i> was created in 2023 to help students worldwide suffering from mental illness. Pressure generated by parents, society and our peers can be sometimes too hard for us to handle which may lead to adverse steps one may take. We provide a platform to help connect people suffering from depression and anxiety as well as experts who help them overcome situations and help them relax for a bit. We often personally meet with clients, and speak at educational events on “Severe depression conditions”</div>

<div className='flex'><h1 className='text-xl font-bold'>Email :</h1> <div className='ml-2'> shresthm727@gmail.com</div></div>

<div className='flex flex-col gap-2'><h1 className='text-xl font-bold'>What you get when asking Your Question</h1>
<ul className='list-disc ml-4'>
    <li>Less than 12-hour repsonse to your question</li>
    <li>Thoroughness and expertise of a Certified Physchologist®</li>
    <li>Plan of action summarized in an email follow up</li>
</ul>
</div>

<div className='help_contact'>

<form className='half_ips flex flex-wrap'>
    <label htmlFor='f_name'  className='width_half'>
        <h1 className='text-xl font-normal'>First Name</h1>
        <div><input name='f_name' className='help_ip'></input></div>
    </label>

    <label htmlFor='l_name' className='width_half'>
        <h1 className='text-xl font-normal'>Last Name</h1>
        <div><input name='l_name' className='help_ip'></input></div>
    </label>

    <label htmlFor='email_add' className='width_half'>
        <h1 className='text-xl font-normal'>Email Address</h1>
        <div><input name='email_add' className='help_ip'></input></div>
    </label>

    <label htmlFor='pn_number' className='width_half'>
        <h1 className='text-xl font-normal'>Phone Number</h1>
        <div><input name='pn_number' className='help_ip'></input></div>
    </label>

    <label htmlFor='issues' className='please'>
        <h1 className='text-xl font-normal'>Please tell the issues your are facing: </h1>
        <div>  
  <select name="issues" id="cars" className='full_help_ip mt-2'>
    <option value="Depressed">Depressed</option>
    <option value="Burnt Out">Burn Out</option>
    <option value="Pressure">Pressure</option>
    <option value="Lonely">Lonely</option>
  </select></div>
    </label>

    <label htmlFor='identify' className='please'>
        <h1 className='text-xl font-normal'>How do we identify you as: </h1>
        <div>  
  <select name="identify" id="cars" className='full_help_ip mt-2'>
    <option value="High School Student">High School Student</option>
    <option value="College Student">College Student</option>
    <option value="Graduate">Graduate</option>
    <option value="Retired">Retired</option>
  </select></div>
    </label>

<label htmlFor='ip_textarea' className='please'>
    <h1 className='text-xl font-normal'>Please explain Your issue in short and how we may help you</h1>
    <div>
        <textarea name='ip_textarea' rows={'10'} className='txarea' style={{border:'1px solid black',padding:'10px'}} ></textarea>
    </div>
</label>

<div className='submit_btn'><button className='help_btn'>Send</button></div>

</form>


</div>

</div>



<div className='s_helpcon flex flex-col'>
<img src={Help_img} className='s_images'></img>
<div className='s_blogs'></div>
<img src={Helpful} className='s_images'></img>
</div>

    </div>
    </div>
    </>

  )
}

export default Help;
